# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          #- npm install
          #- npm test
          - echo $DEPLOY_USERNAME
          
          - git config --global credential.helper cache
          # Set git to use the credential memory cache
          
          - git --global config user.name "nathanhiemstra"
          - git --global config user.email "nayt@s4dc.org"
          - git config user.name "$DEPLOY_USERNAME"
          - git config user.email "$DEPLOY_EMAIL"
          - git add package.json
          - git commit -m "[skip CI]"
          - git push
          - git config --list